### ISSUE TITLE
https browser and embedded device net::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by flatmax** [vphantom/js-jrpc#13]
We are sourceing pages in the browser using https. For that reason we need to use secure ws (wss). Our embedded devices are on a LAN (192.168.0.* ip addresses).

When the browser tries to connect a wss to the embedded device, we get the error net::ERR_CERT_AUTHORITY_INVALID

We are having trouble working out how to generate the embedded side certification  which allows the browser to connect using wss.

Is there a simple standard way to do this ?
Currently we have been trying to self sign certificates... however we aren't having much luck.

**Comment by vphantom** [comment]
Modern browsers are making it near-impossible to use self-signed certificates, even for testing purposes.

Especially if you want any browser (not just one under your control) to access the service, you'd be better off using an authority like [Let's Encrypt](https://letsencrypt.org/) to generate "proper" certificates for your service.  In addition to being free, Let's Encrypt is widely recognized and offers many of ways to automate generating and renewing their certificates.
