### ISSUE TITLE
remote.notfiy request should not contain id

### ISSUE THREAD

**Issue by jamchen** [vphantom/js-jrpc#8]
As a JSON-RPC 2.0 Notification, the request should not contain id field and if remote.notfiy is intentionally to be an interface to send notification.

Reference: http://www.jsonrpc.org/specification#notification

BTW, I love this module. Easy to use and easy to integrate with other transport methods.
Thank you, cheers.

**Comment by vphantom** [comment]
Good catch, and thank you. :smiley: It should be trivial to fix; I'll look over it this weekend.

**Comment by jamchen** [comment]
My pleasure :)

**Comment by vphantom** [comment]
This morning's release 3.1.1 should address the issue.

**Comment by jamchen** [comment]
Cool!
